version: '3.10'

services:

  db:
    image: postgres:14.3-alpine3.16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: fucking_spilberg
      POSTGRES_DB: ntl_aiohttp
